Pin version of activesupport to install
The kubeclient gem does not specify what version of activesupport to install, and it's currently on 2.2 Ruby only:

ERROR:  Error installing kubeclient:
	activesupport requires Ruby version >= 2.2.2.

So we can specify an older version first